[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "backend-fastapi"
version = "0.0.1"
description = "Minimal FastAPI app for Linkyard"
readme = "README.md"
license = { text = "MIT" }
